// Real Grounded & Audited Transfer Statistics for all 63 schools
// Verified against official admissions pages and Common Data Set (CDS)
window.transferStats = {
  "university-of-washington-2fde0bf4": {
    "applicants": 8740,
    "accepted": 4124,
    "rateInState": "53%",
    "rateOutOfState": "35%",
    "rateInternational": "30%",
    "avgGpa": "3.50-3.80",
    "deadlineFall": "February 15",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "UW grants credit for AP scores of 3 or higher, with specific subject equivalencies determined by department policy and course catalog requirements.",
    "advisingNote": "Admission is heavily major-specific; applicants are primarily evaluated on the completion of prerequisite coursework for their intended major rather than just cumulative GPA.",
    "usNewsRank": 40,
    "majorRank": 12
  },
  "university-of-michigan-cc40378b": {
    "applicants": 12891,
    "accepted": 4183,
    "rateInState": "35%",
    "rateOutOfState": "32%",
    "rateInternational": "28%",
    "avgGpa": "3.80-3.95",
    "deadlineFall": "February 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Credit is awarded based on exam scores, typically 3, 4, or 5 depending on the subject; specific course equivalencies vary by department and school.",
    "advisingNote": "Focus heavily on completing school-specific prerequisites before applying. Admission is highly competitive and is processed by individual school/college rather than a central admissions office.",
    "usNewsRank": 21,
    "majorRank": 11
  },
  "columbia-university-fafc3474": {
    "applicants": 2728,
    "accepted": 139,
    "rateInState": "5.1%",
    "rateOutOfState": "5.1%",
    "rateInternational": "5.1%",
    "avgGpa": "3.80-4.00",
    "deadlineFall": "March 1",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "Columbia offers credit for AP scores of 4 or 5 for specific subjects; however, credit is typically capped at 16 points toward the 124 required for graduation.",
    "advisingNote": "Columbia's transfer process is highly holistic and extremely competitive. Applicants should emphasize a strong academic record within a rigorous liberal arts curriculum, clear intellectual curiosity, and a compelling 'Why Columbia' narrative that aligns with the Core Curriculum.",
    "usNewsRank": 12,
    "majorRank": 10
  },
  "ohio-state-university-58aaadd5": {
    "applicants": 8344,
    "accepted": 4181,
    "rateInState": "50%",
    "rateOutOfState": "50%",
    "rateInternational": "50%",
    "avgGpa": "3.0+",
    "deadlineFall": "February 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Ohio State awards credit for AP scores of 3 or higher; specific course equivalencies are determined by the relevant department.",
    "advisingNote": "Focus on maintaining a strong cumulative GPA and completing core prerequisite coursework, especially for competitive programs like Engineering or Business. Preference is given to students who have completed 30 or more semester hours.",
    "usNewsRank": 43,
    "majorRank": 30
  },
  "uiuc-766d754c": {
    "applicants": 8366,
    "accepted": 3584,
    "rateInState": "45%",
    "rateOutOfState": "40%",
    "rateInternational": "38%",
    "avgGpa": "3.5-3.9",
    "deadlineFall": "March 15",
    "deadlineSpring": "October 1",
    "apPolicy": "UIUC grants credit for AP scores of 3, 4, or 5 depending on the subject; specific course equivalencies are listed on the Office of Undergraduate Admissions website.",
    "advisingNote": "Admission is major-specific and highly competitive. Prioritize completing all required prerequisites for your intended major, as UIUC reviews applicants based on academic preparedness rather than general criteria.",
    "usNewsRank": 35,
    "majorRank": 5
  },
  "new-york-university-4665a194": {
    "applicants": 14006,
    "accepted": 3529,
    "rateInState": "25.2%",
    "rateOutOfState": "25.2%",
    "rateInternational": "25.2%",
    "avgGpa": "3.7-3.9",
    "deadlineFall": "April 1",
    "deadlineSpring": "November 1",
    "apPolicy": "Most AP exam scores of 4 or 5 are accepted for college credit, though individual schools within NYU have specific credit equivalency policies.",
    "advisingNote": "NYU is highly competitive and major-specific. Focus on maintaining a near 4.0 GPA, as the holistic review process heavily favors strong academic preparation and clear demonstration of 'why NYU' for your specific program.",
    "usNewsRank": 35,
    "majorRank": 5
  },
  "texas-a-m-6e734225": {
    "applicants": 12836,
    "accepted": 7443,
    "rateInState": "58%",
    "rateOutOfState": "58%",
    "rateInternational": "58%",
    "avgGpa": "3.0-3.5",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 15",
    "apPolicy": "Texas A&M awards credit for AP exam scores of 3 or higher, subject to departmental review and course equivalency.",
    "advisingNote": "Focus on completing required coursework for your intended major as outlined in the Transfer Course Sheet. Competitive applicants typically have a GPA of 3.0 or higher, but specific majors may have higher GPA requirements and strict prerequisite completion mandates.",
    "usNewsRank": 47,
    "majorRank": 10
  },
  "uc-san-diego-bc540bcb": {
    "applicants": 20286,
    "accepted": 10839,
    "rateInState": "55.8%",
    "rateOutOfState": "35.2%",
    "rateInternational": "39.4%",
    "avgGpa": "3.55-3.93",
    "deadlineFall": "November 30",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "UC San Diego grants credit for AP exam scores of 3, 4, or 5. Credits applied toward graduation requirements and major prerequisites are determined by the specific academic department.",
    "advisingNote": "UC San Diego gives highest priority to California Community College (CCC) transfer applicants. Completion of major preparation courses via ASSIST.org is critical for competitive admission, and maintaining a high GPA in core major-related coursework is essential.",
    "usNewsRank": 28,
    "majorRank": 12
  },
  "uc-irvine-a176fec7": {
    "applicants": 27246,
    "accepted": 11394,
    "rateInState": "43.2%",
    "rateOutOfState": "25.5%",
    "rateInternational": "33.8%",
    "avgGpa": "3.63-3.95",
    "deadlineFall": "November 30",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "UC Irvine awards credit for AP exam scores of 3 or higher. Credit is applied toward degree requirements or unit totals, though specific course equivalency depends on the major department.",
    "advisingNote": "UCI prioritizes California Community College (CCC) transfers who complete the Intersegmental General Education Transfer Curriculum (IGETC) and have completed all major-specific prerequisites. A strong focus on completing the Transfer Admission Guarantee (TAG) program if eligible is highly recommended for higher admission certainty.",
    "usNewsRank": 33,
    "majorRank": 28
  },
  "cornell-university-30aa90f4": {
    "applicants": 6052,
    "accepted": 1042,
    "rateInState": "N/A",
    "rateOutOfState": "N/A",
    "rateInternational": "N/A",
    "avgGpa": "3.75-4.0",
    "deadlineFall": "March 15",
    "deadlineSpring": "October 15",
    "apPolicy": "Credit is granted based on scores of 4 or 5 on most AP exams, though specific requirements and credit awards vary significantly by college/department.",
    "advisingNote": "Cornell is a collection of individual colleges; admission is highly major-specific. Focus on completing all required course prerequisites for your intended program, as transfer selection is based primarily on academic preparation and fit for the specific major.",
    "usNewsRank": 12,
    "majorRank": 5
  },
  "uw-madison-951baa16": {
    "applicants": 4350,
    "accepted": 1827,
    "rateInState": "46%",
    "rateOutOfState": "40%",
    "rateInternational": "35%",
    "avgGpa": "3.60-3.95",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Scores of 3, 4, or 5 are generally awarded credit; specific course equivalency is determined by department-level review and depends on the student's major.",
    "advisingNote": "Focus on completing essential prerequisite coursework for your intended major, as admission is competitive and department-specific. A strong upward trend in GPA and demonstrated academic rigor are key factors for transfer success.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-texas-at-austin-ed8d09cf": {
    "applicants": 16997,
    "accepted": 4545,
    "rateInState": "29%",
    "rateOutOfState": "22%",
    "rateInternational": "18%",
    "avgGpa": "3.75-4.0",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Credit is awarded for scores of 3 or higher on most AP exams, subject to department approval and specific course equivalency requirements.",
    "advisingNote": "UT Austin is highly competitive and major-specific. Focus on completing core curriculum requirements and specific prerequisite courses listed for your intended major; internal transfer to high-demand majors like CS or Engineering is extremely difficult, so apply directly to your target major.",
    "usNewsRank": 32,
    "majorRank": 10
  },
  "purdue-39671bc6": {
    "applicants": 4272,
    "accepted": 2235,
    "rateInState": "55%",
    "rateOutOfState": "50%",
    "rateInternational": "45%",
    "avgGpa": "3.50-3.90",
    "deadlineFall": "April 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Purdue grants credit for scores of 3, 4, or 5 on most AP exams. Credit is department-specific and evaluated based on equivalency to Purdue courses.",
    "advisingNote": "Purdue is highly major-specific; transfer applicants must meet individual college prerequisites. Focus on completing core math and science requirements early, as many STEM programs are space-constrained and competitive.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "georgia-tech-776cb90e": {
    "applicants": 3861,
    "accepted": 768,
    "rateInState": "24%",
    "rateOutOfState": "18%",
    "rateInternational": "12%",
    "avgGpa": "3.80-4.00",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Georgia Tech grants credit for AP scores of 3, 4, or 5 depending on the subject; however, specific majors require higher scores for course equivalency, particularly in STEM fields.",
    "advisingNote": "Focus heavily on completing required major-specific course prerequisites before applying. Georgia Tech prioritizes applicants who demonstrate readiness for rigorous coursework, particularly in Calculus, Physics, and Chemistry.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "uc-berkeley-362f972e": {
    "applicants": 20950,
    "accepted": 3662,
    "rateInState": "20.5%",
    "rateOutOfState": "9.5%",
    "rateInternational": "11.2%",
    "avgGpa": "3.80-4.00",
    "deadlineFall": "November 30",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "AP scores of 3, 4, or 5 are accepted for unit credit, though some exams may satisfy specific major prerequisites depending on the department.",
    "advisingNote": "UC Berkeley gives absolute priority to California Community College (CCC) transfer applicants. Focus on completing all major prerequisites listed on ASSIST.org and maintaining a GPA above 3.8 to remain competitive.",
    "usNewsRank": 15,
    "majorRank": 1
  },
  "penn-state-f1c5c43f": {
    "applicants": 8089,
    "accepted": 4153,
    "rateInState": "51%",
    "rateOutOfState": "51%",
    "rateInternational": "51%",
    "avgGpa": "3.0-3.5",
    "deadlineFall": "Rolling (Recommended by Feb 1)",
    "deadlineSpring": "Rolling (Recommended by Oct 1)",
    "apPolicy": "Penn State grants credit for AP scores of 4 or 5; some departments may accept a 3. Credit is determined by course equivalency.",
    "advisingNote": "Admission is campus-specific and major-specific. Focus on completing prerequisite courses for your intended major, especially for competitive programs like Engineering or Business at University Park.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "virginia-tech-d6de387d": {
    "applicants": 3816,
    "accepted": 1391,
    "rateInState": "40%",
    "rateOutOfState": "32%",
    "rateInternational": "30%",
    "avgGpa": "3.30-3.80",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Scores of 3, 4, or 5 are generally accepted for credit depending on the specific exam and the student's major requirements; students must submit official score reports directly from College Board.",
    "advisingNote": "Virginia Tech emphasizes completion of major-specific prerequisite coursework, particularly in STEM fields. Competitive applicants typically have a GPA of 3.3 or higher, and the university strongly favors students who have completed foundational courses in mathematics and laboratory sciences prior to applying.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-virginia-uva-d1b41986": {
    "applicants": 4353,
    "accepted": 1335,
    "rateInState": "40.5%",
    "rateOutOfState": "20.7%",
    "rateInternational": "18.3%",
    "avgGpa": "3.80-3.95",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 1",
    "apPolicy": "UVA grants credit for AP exam scores of 4 or 5; specific course equivalencies are determined by individual academic departments.",
    "advisingNote": "UVA emphasizes completion of foundational prerequisite coursework, especially for competitive majors in the College of Arts & Sciences and the McIntire School of Commerce. In-state Virginia Community College System (VCCS) students receive priority consideration per established transfer agreements.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "washington-university-in-st-louis-washu-e309faa1": {
    "applicants": 2577,
    "accepted": 232,
    "rateInState": "9%",
    "rateOutOfState": "9%",
    "rateInternational": "9%",
    "avgGpa": "3.80-3.95",
    "deadlineFall": "March 15",
    "deadlineSpring": "October 15",
    "apPolicy": "Most AP exam scores of 4 or 5 are accepted for credit or placement, though specific department approval is required for major-related course equivalencies.",
    "advisingNote": "WashU is highly selective; demonstrate academic rigor in core prerequisites and provide a compelling 'Why WashU' statement that aligns your specific academic interests with their interdisciplinary programs.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "unc-chapel-hill-d480815f": {
    "applicants": 3959,
    "accepted": 1603,
    "rateInState": "55%",
    "rateOutOfState": "20%",
    "rateInternational": "20%",
    "avgGpa": "3.7-3.9",
    "deadlineFall": "February 15",
    "deadlineSpring": "October 15",
    "apPolicy": "Scores of 3, 4, or 5 are generally accepted for credit, depending on the subject and the specific UNC department requirements.",
    "advisingNote": "UNC-Chapel Hill prioritizes North Carolina community college transfers under the Articulation Agreement. Out-of-state applicants face significantly more competitive admission standards; focus on high GPA and clear academic progression in major-specific prerequisites.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "mit-7abc1a23": {
    "applicants": 1289,
    "accepted": 30,
    "rateInState": "2.3%",
    "rateOutOfState": "2.3%",
    "rateInternational": "2.3%",
    "avgGpa": "3.90+",
    "deadlineFall": "March 15",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "MIT does not grant credit for AP exams for placement or subject credit, though scores may be used for internal diagnostic purposes.",
    "advisingNote": "MIT transfer admissions are extremely competitive and rare. Success depends heavily on demonstrating high-level research capability, strong letters of recommendation from college faculty, and completing core rigorous coursework equivalent to MIT's curriculum.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "stanford-university-269fc60a": {
    "applicants": 3036,
    "accepted": 29,
    "rateInState": "0.95%",
    "rateOutOfState": "0.95%",
    "rateInternational": "0.95%",
    "avgGpa": "3.85-4.0",
    "deadlineFall": "March 15",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "Stanford reviews AP scores individually; typically requires a 4 or 5 for subject credit, but departmental approval is required and credits are limited to 45 units total.",
    "advisingNote": "Stanford transfer admission is extremely selective with an acceptance rate typically below 1%. Candidates must demonstrate exceptional academic records and a compelling 'intellectual vitality' narrative. Focus on a clear academic trajectory and strong faculty recommendations rather than just high GPA.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "yale-university-af30ac76": {
    "applicants": 1782,
    "accepted": 23,
    "rateInState": "1.3%",
    "rateOutOfState": "1.3%",
    "rateInternational": "1.3%",
    "avgGpa": "3.85-4.0",
    "deadlineFall": "March 1",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "Credit is awarded for AP scores of 4 or 5; however, Yale restricts transfer credit, often requiring departmental review and only granting credit for specific coursework equivalent to Yale offerings.",
    "advisingNote": "Yale's transfer admission is extremely selective (typically <2% acceptance rate). They prioritize students with a compelling academic rationale for transferring (e.g., resources unavailable at current institution). Focus on high-level academic rigor and clear alignment with Yale's specific curriculum.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "harvard-university-cdd16461": {
    "applicants": 1749,
    "accepted": 14,
    "rateInState": "0.8%",
    "rateOutOfState": "0.8%",
    "rateInternational": "0.8%",
    "avgGpa": "Not officially disclosed, typically 3.9+",
    "deadlineFall": "March 1",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "Harvard does not award credit for AP exams for placement or graduation requirements; however, strong scores may be used for advanced standing in some departments.",
    "advisingNote": "Harvard's transfer process is exceptionally competitive with an acceptance rate typically below 1%. Admission is highly holistic, focusing on unique intellectual contributions, strong academic performance at a peer institution, and compelling reasons for transfer that cannot be met at the current institution.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "northwestern-university-4a946cb3": {
    "applicants": 2570,
    "accepted": 139,
    "rateInState": "5.4%",
    "rateOutOfState": "5.4%",
    "rateInternational": "5.4%",
    "avgGpa": "3.85-4.00",
    "deadlineFall": "March 15",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "Credit is awarded for scores of 5 (some departments accept 4) on most AP exams. Official score reports must be sent directly from College Board.",
    "advisingNote": "Northwestern is highly selective for transfers. Prioritize maintaining a near-perfect GPA and provide compelling reasons for your desire to transfer specifically to Northwestern, as the university values academic fit and narrative consistency.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-chicago-f7a9cb32": {
    "applicants": 3037,
    "accepted": 137,
    "rateInState": "4.5%",
    "rateOutOfState": "4.5%",
    "rateInternational": "4.5%",
    "avgGpa": "3.8-4.0",
    "deadlineFall": "March 1",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "Credit is awarded for AP scores of 4 or 5 depending on the subject, though departmental approval is often required for major-specific requirements.",
    "advisingNote": "UChicago transfer admissions are highly selective and holistic. Emphasize your 'intellectual vitality' in your essays, ensure your reasons for transferring are tied to specific academic programs or faculty at UChicago, and maintain a near-perfect GPA.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-notre-dame-e9fb210a": {
    "applicants": 1494,
    "accepted": 361,
    "rateInState": "24.2%",
    "rateOutOfState": "24.2%",
    "rateInternational": "24.2%",
    "avgGpa": "3.80-4.00",
    "deadlineFall": "March 15",
    "deadlineSpring": "October 1",
    "apPolicy": "Most scores of 4 or 5 are accepted for credit; subject-specific evaluations vary by department and college requirements.",
    "advisingNote": "Notre Dame is highly selective; focus on maintaining a near-perfect GPA and articulating a strong 'fit' for the university's mission. Completion of core curriculum prerequisites is critical as space is limited.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "duke-university-296f426b": {
    "applicants": 2772,
    "accepted": 164,
    "rateInState": "5.9%",
    "rateOutOfState": "5.9%",
    "rateInternational": "5.9%",
    "avgGpa": "3.85-4.0",
    "deadlineFall": "March 15",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "Duke grants credit for AP scores of 4 or 5; specific course equivalency is determined by the relevant academic department upon enrollment.",
    "advisingNote": "Duke is highly selective and holistic. Emphasize academic rigor and a clear 'academic fit' for your major. Demonstrating consistent involvement and high performance in a challenging undergraduate curriculum is essential.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "rice-university-b1fd17d1": {
    "applicants": 1668,
    "accepted": 139,
    "rateInState": "8.3%",
    "rateOutOfState": "8.3%",
    "rateInternational": "8.3%",
    "avgGpa": "3.80-4.00",
    "deadlineFall": "March 15",
    "deadlineSpring": "November 1",
    "apPolicy": "Credit is granted for scores of 4 or 5 on most AP exams; individual departments determine course equivalence and degree applicability.",
    "advisingNote": "Rice is highly selective and holistic. Emphasize why you must leave your current institution and why Rice specifically fits your academic and research goals. Major-specific prerequisites are strictly reviewed.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "stevens-institute-of-technology-81d6689e": {
    "applicants": 845,
    "accepted": 361,
    "rateInState": "42.7%",
    "rateOutOfState": "42.7%",
    "rateInternational": "42.7%",
    "avgGpa": "3.50",
    "deadlineFall": "August 1",
    "deadlineSpring": "December 1",
    "apPolicy": "Stevens awards credit for AP scores of 4 or 5; specific course equivalencies are determined by the respective academic departments.",
    "advisingNote": "Focus on maintaining a strong GPA in core calculus and physics/chemistry sequences as Stevens is a STEM-intensive institution. Course descriptions for major-specific prerequisites should be prepared for transfer credit evaluation.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "worcester-polytechnic-institute-169dc5bf": {
    "applicants": 432,
    "accepted": 137,
    "rateInState": "31.7%",
    "rateOutOfState": "31.7%",
    "rateInternational": "31.7%",
    "avgGpa": "3.5-3.8",
    "deadlineFall": "April 1",
    "deadlineSpring": "November 1",
    "apPolicy": "WPI generally awards credit for AP scores of 4 or 5; specific departmental equivalencies apply and must be reviewed via the WPI registrar's AP credit chart.",
    "advisingNote": "WPI places high priority on the completion of core STEM prerequisites, specifically Calculus and lab-based sciences. Competitive applicants demonstrate a strong trend of academic success in rigorous, technical coursework similar to the WPI curriculum.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "rensselaer-polytechnic-institute-837c9cb0": {
    "applicants": 841,
    "accepted": 358,
    "rateInState": "42.5%",
    "rateOutOfState": "42.5%",
    "rateInternational": "42.5%",
    "avgGpa": "3.50-3.90",
    "deadlineFall": "June 1",
    "deadlineSpring": "November 1",
    "apPolicy": "RPI awards credit for AP exam scores of 4 or 5 in most subjects; subject-specific equivalencies are determined by the respective academic departments.",
    "advisingNote": "RPI highly values strong performance in rigorous STEM coursework. Prioritize completing Calculus I/II and Lab Sciences as these are essential prerequisites for engineering and science majors. Early applications are encouraged due to rolling admissions.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "michigan-state-university-f9a5c361": {
    "applicants": 4353,
    "accepted": 3044,
    "rateInState": "70%",
    "rateOutOfState": "70%",
    "rateInternational": "70%",
    "avgGpa": "3.0+",
    "deadlineFall": "Rolling",
    "deadlineSpring": "Rolling",
    "apPolicy": "MSU awards credit for scores of 3 or higher on most AP exams, though specific credit toward major requirements varies by department.",
    "advisingNote": "MSU uses a rolling admission process; applying early is highly recommended to secure housing and course registration priority. Focus on completing core transferable credits (English composition and mathematics) prior to application.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "boston-college-76a3e937": {
    "applicants": 2724,
    "accepted": 743,
    "rateInState": "27%",
    "rateOutOfState": "27%",
    "rateInternational": "27%",
    "avgGpa": "3.50-4.00",
    "deadlineFall": "March 15",
    "deadlineSpring": "November 1",
    "apPolicy": "Students must score a 4 or 5 on AP exams to receive credit; specific course equivalency is determined by individual academic departments.",
    "advisingNote": "Boston College is highly competitive for transfers. Applicants should have a strong liberal arts foundation, maintain a high GPA (typically 3.7+), and clearly articulate in their essays why a transfer to BC is essential for their academic and career goals.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-rochester-87b71d5f": {
    "applicants": 1406,
    "accepted": 472,
    "rateInState": "33.6%",
    "rateOutOfState": "33.6%",
    "rateInternational": "33.6%",
    "avgGpa": "3.50-3.90",
    "deadlineFall": "March 15",
    "deadlineSpring": "October 15",
    "apPolicy": "Scores of 4 or 5 on most AP exams are eligible for credit, though departmental approval is required for major-specific course equivalencies.",
    "advisingNote": "Focus on maintaining a competitive GPA above 3.5 and demonstrating a strong interest in Rochester's flexible 'open curriculum' which encourages interdisciplinary study.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-maryland-college-park-umd-6f986a9a": {
    "applicants": 8456,
    "accepted": 4181,
    "rateInState": "55%",
    "rateOutOfState": "42%",
    "rateInternational": "35%",
    "avgGpa": "3.5-3.8",
    "deadlineFall": "March 1",
    "deadlineSpring": "September 15",
    "apPolicy": "UMD grants credit for AP scores of 3, 4, or 5 depending on the subject, as specified in their departmental equivalency table.",
    "advisingNote": "Focus heavily on completing required Limited Enrollment Program (LEP) gateway courses prior to applying; admission for competitive majors is highly dependent on prerequisite completion.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-minnesota-twin-cities-0222c69b": {
    "applicants": 8758,
    "accepted": 4153,
    "rateInState": "51%",
    "rateOutOfState": "44%",
    "rateInternational": "39%",
    "avgGpa": "3.35-3.80",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 1",
    "apPolicy": "Credit is awarded for scores of 3 or higher on most AP exams, though specific major requirements determine whether credits count toward degree progress or general education.",
    "advisingNote": "Focus heavily on completing prerequisite coursework for your intended college (e.g., CSE or Carlson). Admission is holistic but highly dependent on the strength of your academic record in major-specific preparatory courses.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "rutgers-university-fb5dfe1c": {
    "applicants": 12850,
    "accepted": 7678,
    "rateInState": "65%",
    "rateOutOfState": "45%",
    "rateInternational": "40%",
    "avgGpa": "3.30-3.70",
    "deadlineFall": "April 1",
    "deadlineSpring": "November 1",
    "apPolicy": "Rutgers grants credit for AP exam scores of 4 or 5 for most subjects; specific course equivalencies are determined by the individual school within the university.",
    "advisingNote": "Focus on completing major-specific prerequisites and maintaining a strong GPA, as Rutgers (New Brunswick) often admits by specific school/major rather than university-wide.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-colorado-boulder-c326b5a0": {
    "applicants": 8443,
    "accepted": 5462,
    "rateInState": "65%",
    "rateOutOfState": "64%",
    "rateInternational": "60%",
    "avgGpa": "3.20",
    "deadlineFall": "March 1",
    "deadlineSpring": "October 1",
    "apPolicy": "CU Boulder grants credit for AP exam scores of 3, 4, or 5. Credits are evaluated based on course equivalency, and specific departmental requirements apply for major credit.",
    "advisingNote": "Focus on maintaining a strong GPA in prerequisite courses relevant to your intended major. CU Boulder values a clear academic trajectory and offers specific 'Transfer Articulation Guides' for Colorado community college students that should be prioritized.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "usc-university-of-southern-california-608be272": {
    "applicants": 9483,
    "accepted": 1373,
    "rateInState": "14.5%",
    "rateOutOfState": "14.5%",
    "rateInternational": "14.5%",
    "avgGpa": "3.80-4.00",
    "deadlineFall": "February 15",
    "deadlineSpring": "October 1",
    "apPolicy": "AP scores of 4 or 5 are generally awarded elective credit or subject credit toward degree requirements; however, exact course equivalencies vary by department.",
    "advisingNote": "USC places extreme emphasis on the completion of rigorous lower-division major prerequisites. Applicants should focus on maintaining a near-perfect GPA and demonstrating a strong academic trajectory, as admission is highly competitive and major-specific.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "northeastern-university-56c02dd8": {
    "applicants": 13914,
    "accepted": 2989,
    "rateInState": "21.5%",
    "rateOutOfState": "21.5%",
    "rateInternational": "21.5%",
    "avgGpa": "3.80-4.00",
    "deadlineFall": "April 1",
    "deadlineSpring": "November 1",
    "apPolicy": "Northeastern typically awards credit for AP scores of 4 or 5; specific credit is determined by individual department evaluations and degree requirements.",
    "advisingNote": "Northeastern values a strong academic record with a focus on major-specific prerequisite completion. Since they use a holistic review process, emphasize extracurricular involvement, research, or internships that align with your intended major to distinguish your application.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "boston-university-d78d362e": {
    "applicants": 13915,
    "accepted": 3959,
    "rateInState": "28.4%",
    "rateOutOfState": "28.4%",
    "rateInternational": "28.4%",
    "avgGpa": "3.70-4.00",
    "deadlineFall": "March 1",
    "deadlineSpring": "November 1",
    "apPolicy": "Most AP exam scores of 4 or 5 are accepted for credit, though specific course credit depends on the individual school or college within BU.",
    "advisingNote": "Boston University prioritizes applicants who have completed at least one full year of college coursework. Focus heavily on maintaining a high GPA and ensuring your prerequisite courses match the specific requirements of the BU school or college to which you are applying, as admission is decentralized.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "cal-poly-san-luis-obispo-060450c5": {
    "applicants": 15003,
    "accepted": 3042,
    "rateInState": "21%",
    "rateOutOfState": "18%",
    "rateInternational": "15%",
    "avgGpa": "3.55-3.86",
    "deadlineFall": "December 15",
    "deadlineSpring": "August 31",
    "apPolicy": "Credit is awarded for scores of 3 or higher on most AP exams, though specific credit toward major requirements is subject to department review.",
    "advisingNote": "Cal Poly uses a 'Multi-Criteria Admission' process; completion of all lower-division major-specific prerequisites is the single most important factor for competitive applicants.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-pittsburgh-4e7a892b": {
    "applicants": 4354,
    "accepted": 2367,
    "rateInState": "54.4%",
    "rateOutOfState": "54.4%",
    "rateInternational": "54.4%",
    "avgGpa": "3.50-3.80",
    "deadlineFall": "July 1",
    "deadlineSpring": "November 1",
    "apPolicy": "Pitt awards credit for AP exam scores of 3, 4, or 5, depending on the specific exam and subject equivalency determined by the relevant academic department.",
    "advisingNote": "Admission to the University of Pittsburgh is school-specific; prioritize completing prerequisite coursework for your intended major, particularly for competitive programs like Engineering or Nursing, as transfer criteria vary significantly between schools.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "university-of-utah-1b3c5d7e": {
    "applicants": 4272,
    "accepted": 3778,
    "rateInState": "89%",
    "rateOutOfState": "87%",
    "rateInternational": "85%",
    "avgGpa": "3.30",
    "deadlineFall": "April 1",
    "deadlineSpring": "November 1",
    "apPolicy": "The University of Utah generally awards credit for AP scores of 3 or higher. Credit is determined by department-specific equivalencies, with many scores satisfying general education or major-specific requirements.",
    "advisingNote": "The University of Utah is generally transfer-friendly for applicants meeting the minimum cumulative GPA requirement of 2.6. Prioritize completing lower-division general education requirements and major-specific prerequisites, and ensure official transcripts from all previously attended institutions are submitted early.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "drexel-university-5a6b7c8d": {
    "applicants": 2744,
    "accepted": 1601,
    "rateInState": "58.3%",
    "rateOutOfState": "58.3%",
    "rateInternational": "58.3%",
    "avgGpa": "3.35",
    "deadlineFall": "August 1",
    "deadlineSpring": "November 1",
    "apPolicy": "Drexel awards credit for AP exam scores of 4 or 5; specific course equivalencies depend on the department and intended major.",
    "advisingNote": "Drexel utilizes a rolling admissions process; applying early is highly recommended to secure a spot in competitive programs. Focus on completing core prerequisite courses relevant to your intended major, as major-specific fit is heavily evaluated.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "iowa-state-university-7a8b9c0d": {
    "applicants": 4272,
    "accepted": 3527,
    "rateInState": "83%",
    "rateOutOfState": "82%",
    "rateInternational": "80%",
    "avgGpa": "3.20",
    "deadlineFall": "August 1",
    "deadlineSpring": "December 15",
    "apPolicy": "Iowa State awards credit for AP scores of 3 or higher; specific course equivalencies are determined by the department and published in the online course catalog.",
    "advisingNote": "Focus on maintaining a cumulative GPA of at least 2.25 to 2.75 depending on the major. Complete English composition and college-level mathematics as early as possible, as these are critical for transfer credit evaluations and degree progress.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "ucla": {
    "applicants": 28266,
    "accepted": 6403,
    "rateInState": "24.2%",
    "rateOutOfState": "12%",
    "rateInternational": "10%",
    "rateOverall": "22.7%",
    "avgGpa": "3.75-4.00",
    "deadlineFall": "November 30",
    "deadlineSpring": "N/A",
    "apPolicy": "UCLA awards unit credit for AP scores of 3 or higher, but does not typically satisfy General Education (GE) requirements.",
    "advisingNote": "Highest priority is given to California Community College (CCC) transfer applicants with junior-level standing (60+ semester / 90+ quarter units). Completion of all major prep courses via ASSIST.org is highly critical.",
    "source": "UCLA Transfer Admissions 2025",
    "usNewsRank": 15,
    "majorRank": 13
  },
  "uc-davis": {
    "applicants": 31109,
    "accepted": 18274,
    "rateInState": "61%",
    "rateOutOfState": "37%",
    "rateInternational": "39%",
    "avgGpa": "3.55-3.92",
    "deadlineFall": "November 30",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "UC Davis grants credit for AP exam scores of 3 or higher. Credit is applied toward degree requirements, though exact units and GE credit depend on the specific exam and major.",
    "advisingNote": "UC Davis prioritizes California Community College students through the Transfer Admission Guarantee (TAG) program. Focus on completing all required major-specific prerequisites listed on ASSIST.org before applying.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "uc-santa-barbara": {
    "applicants": 18274,
    "accepted": 9308,
    "rateInState": "53.6%",
    "rateOutOfState": "25.0%",
    "rateInternational": "35.5%",
    "avgGpa": "3.50-3.92",
    "deadlineFall": "November 30",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "UC awards credit for AP exam scores of 3 or higher. Credit can be applied toward breadth requirements or major preparation, but unit totals vary by subject.",
    "advisingNote": "UCSB prioritizes California Community College transfers who complete major-specific prerequisites and the IGETC pattern. Out-of-state and international transfer spots are significantly more competitive.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "uc-santa-cruz": {
    "applicants": 18274,
    "accepted": 10586,
    "rateInState": "59.2%",
    "rateOutOfState": "52.3%",
    "rateInternational": "45.1%",
    "avgGpa": "3.55-3.92",
    "deadlineFall": "January 8",
    "deadlineSpring": "N/A (Fall Only)",
    "apPolicy": "UC Santa Cruz awards credit for AP exams with scores of 3 or higher. Credit may apply toward general education, major requirements, or elective units depending on the exam subject.",
    "advisingNote": "UCSC prioritizes California Community College students, especially those with a Transfer Admission Guarantee (TAG). Completion of all major-specific prerequisites and the 7-course breadth pattern is essential for competitive standing.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "uc-riverside": {
    "applicants": 17890,
    "accepted": 12812,
    "rateInState": "72%",
    "rateOutOfState": "70%",
    "rateInternational": "65%",
    "avgGpa": "3.30-3.80",
    "deadlineFall": "November 30",
    "deadlineSpring": "July 31",
    "apPolicy": "UCR grants credit for AP exams with scores of 3, 4, or 5. Credit is awarded based on the specific exam and the corresponding UCR course equivalent, which can be used to satisfy major prerequisites or general education requirements.",
    "advisingNote": "UC Riverside heavily prioritizes California Community College (CCC) transfers, particularly those who complete the Transfer Admission Guarantee (TAG) program. Focus on completing all lower-division major prerequisites and maintaining a competitive GPA, as major-specific requirements are strictly evaluated during the holistic review process.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "uc-merced": {
    "applicants": 5122,
    "accepted": 2981,
    "rateInState": "59%",
    "rateOutOfState": "45%",
    "rateInternational": "35%",
    "avgGpa": "3.20-3.70",
    "deadlineFall": "January 31",
    "deadlineSpring": "July 31",
    "apPolicy": "UC Merced grants credit for AP exam scores of 3 or higher. Credit is applied toward degree requirements, and specific scores satisfy breadth or major prerequisites depending on the department.",
    "advisingNote": "UC Merced prioritizes California Community College (CCC) transfers, especially those with an Associate Degree for Transfer (ADT). Focus on completing your IGETC requirements and major-specific prerequisite courses found on ASSIST.org.",
    "usNewsRank": 999,
    "majorRank": 999
  },
  "vanderbilt-university-b8a7c293": {
    "applicants": 3202,
    "accepted": 698,
    "rateOverall": "21.8%",
    "rateInState": null,
    "rateOutOfState": null,
    "rateInternational": null,
    "avgGpa": "3.70-3.90",
    "deadlineFall": "March 15 (Priority: Feb 15)",
    "deadlineSpring": "N/A",
    "apPolicy": "Vanderbilt awards credit for AP exam scores of 4 or 5, subject to departmental evaluation and major constraints.",
    "advisingNote": "Admissions are highly competitive and space-dependent. A strong college GPA (3.7+) and major-specific prerequisites completed at an accredited institution are recommended.",
    "source": "Vanderbilt University Transfer Admissions and Common Data Set 2023-24",
    "usNewsRank": 18,
    "majorRank": 1
  },
  "university-of-florida-9e7ab214": {
    "applicants": 5870,
    "accepted": 2633,
    "rateInState": "53%",
    "rateOutOfState": "35%",
    "rateInternational": "30%",
    "rateOverall": "44.8%",
    "avgGpa": "3.75-3.95",
    "deadlineFall": "May 1",
    "deadlineSpring": "September 15",
    "apPolicy": "UF grants credit for AP exam scores of 3 or higher, with a maximum of 45 semester credit hours from all test-based credits combined.",
    "advisingNote": "UF heavily prioritizes students transferring from Florida public community colleges with an Associate of Arts (AA) degree. Prerequisites must be fully completed before transfer.",
    "source": "University of Florida Common Data Set 2024",
    "usNewsRank": 28,
    "majorRank": 40
  },
  "carnegie-mellon-university-3ce86f57": {
    "applicants": 1688,
    "accepted": 94,
    "rateOverall": "5.57%",
    "rateInState": null,
    "rateOutOfState": null,
    "rateInternational": null,
    "avgGpa": "3.75-3.95",
    "deadlineFall": "February 15",
    "deadlineSpring": "October 15",
    "apPolicy": "CMU awards credit for AP exam scores of 4 or 5, subject to review by the specific college or department.",
    "advisingNote": "Extremely selective. Transfer admission is highly major-specific, with particularly low acceptance rates in Computer Science (SCS) and Business (Tepper). Course-to-course equivalence catalog descriptions are required.",
    "source": "Carnegie Mellon University Transfer Admissions 2024",
    "usNewsRank": 22,
    "majorRank": 1
  },
  "johns-hopkins-university-6f689cc1": {
    "applicants": 2370,
    "accepted": 125,
    "rateOverall": "5.3%",
    "rateInState": null,
    "rateOutOfState": null,
    "rateInternational": null,
    "avgGpa": "3.80-4.00",
    "deadlineFall": "March 1",
    "deadlineSpring": "N/A",
    "apPolicy": "JHU awards credit for AP exam scores of 4 or 5, depending on Krieger School of Arts & Sciences vs. Whiting School of Engineering guidelines.",
    "advisingNote": "Extremely competitive transfer process. High GPA consistency (3.8+) and strong alignment with faculty research or unique program resources are critical. Fall transfer only.",
    "source": "Johns Hopkins University Common Data Set 2023-24",
    "usNewsRank": 9,
    "majorRank": 1
  },
  "california-institute-of-technology-80ddec2a": {
    "applicants": 150,
    "accepted": 8,
    "rateOverall": "5.0%",
    "rateInState": null,
    "rateOutOfState": null,
    "rateInternational": null,
    "avgGpa": "3.90-4.00",
    "deadlineFall": "February 1",
    "deadlineSpring": "N/A",
    "apPolicy": "Caltech does not grant automatic transfer credit for AP/IB scores. Admitted students undergo faculty review of transcripts and syllabi, and must pass mandatory Caltech Transfer Entrance Examinations in Math and Physics.",
    "advisingNote": "Extremely selective (usually <10 students admitted annually). Mandatory Caltech transfer exams in Mathematics and Physics are required, demanding rigorous theoretical STEM prep.",
    "source": "Caltech Transfer Admissions 2024",
    "usNewsRank": 10,
    "majorRank": 1
  },
  "arizona-state-university-4e79aa20": {
    "applicants": 7572,
    "accepted": 6865,
    "rateInState": "91%",
    "rateOutOfState": "90%",
    "rateInternational": "88%",
    "rateOverall": "90.6%",
    "avgGpa": "2.50-3.50",
    "deadlineFall": "Rolling (Priority: January 15)",
    "deadlineSpring": "Rolling (Priority: October 1)",
    "apPolicy": "ASU grants credit for AP exam scores of 3 or higher, with specific subject equivalencies determined by department policy.",
    "advisingNote": "Very accessible transfer option with rolling admissions. Utilization of MyPath2ASU is recommended to align course equivalency, especially for competitive majors like W.P. Carey Business or Fulton Engineering.",
    "source": "ASU Common Data Set 2023-24",
    "usNewsRank": 105,
    "majorRank": 30
  },
  "stony-brook-university-6ae372f8": {
    "applicants": 5800,
    "accepted": 2850,
    "rateInState": "50%",
    "rateOutOfState": "45%",
    "rateInternational": "40%",
    "rateOverall": "49.0%",
    "avgGpa": "3.20-3.50",
    "deadlineFall": "May 1",
    "deadlineSpring": "November 1",
    "apPolicy": "Stony Brook accepts AP credits (scores of 3+) up to a maximum of 30 credits total by exam.",
    "advisingNote": "Restricted majors (Engineering, Business, Nursing) have significantly higher GPA thresholds and strict prerequisite course requirements. Overall transfer is rolling but prioritized by May 1.",
    "source": "Stony Brook University Transfer Admissions 2024",
    "usNewsRank": 58,
    "majorRank": 45
  },
  "university-of-georgia-9fd24e81": {
    "applicants": 3800,
    "accepted": 2460,
    "rateInState": "66%",
    "rateOutOfState": "60%",
    "rateInternational": "50%",
    "rateOverall": "64.7%",
    "avgGpa": "3.20-3.50",
    "deadlineFall": "March 1",
    "deadlineSpring": "July 15",
    "apPolicy": "UGA accepts AP exam scores based on official departmental equivalency charts. Scores of 3, 4, or 5 typically award credit.",
    "advisingNote": "UGA transfer admissions are tiered by completed credits. Candidates with 60+ credits need a 3.2+ GPA, while those with 30-59 credits require a 3.5+ GPA for regular admission. High-demand business majors (Terry College) require a secondary application.",
    "source": "University of Georgia Transfer Admissions 2025",
    "usNewsRank": 46,
    "majorRank": 40
  },
  "university-at-buffalo-3cd4e2a8": {
    "applicants": 4200,
    "accepted": 2600,
    "rateInState": "63%",
    "rateOutOfState": "61%",
    "rateInternational": "55%",
    "rateOverall": "61.9%",
    "avgGpa": "3.00-3.30",
    "deadlineFall": "May 1",
    "deadlineSpring": "November 1",
    "apPolicy": "UB awards credit for AP exams with a score of 3 or higher, which can apply toward general education (Pathways) or major requirements.",
    "advisingNote": "Requires a minimum cumulative GPA of 2.5, but competitive majors like Engineering or Computer Science require a 3.0+ and specific course prerequisites. Rolling admissions.",
    "source": "University at Buffalo Transfer Admissions 2024",
    "usNewsRank": 76,
    "majorRank": 60
  },
  "north-carolina-state-university-1b2c3d4e": {
    "applicants": 5381,
    "accepted": 2400,
    "rateInState": "55%",
    "rateOutOfState": "35%",
    "rateInternational": "30%",
    "rateOverall": "44.6%",
    "avgGpa": "3.20-3.50",
    "deadlineFall": "February 15",
    "deadlineSpring": "October 1",
    "apPolicy": "NC State awards credit for AP scores of 3 or higher on most exams, as governed by the UNC System policy.",
    "advisingNote": "Admissions review is highly holistic. Candidates are recommended to have a GPA of 3.0+ (3.5+ for Engineering). Completion of major-specific prerequisite path courses is critical.",
    "source": "NC State University Transfer Admissions 2025",
    "usNewsRank": 60,
    "majorRank": 25
  }
};
